language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  #!/bin/bash
  # fail if any commands fails
  - set -e
  # debug log
  - set -x

  - mkdir -p "$ANDROID_HOME/licenses"
  - rsync -avhP ./android-licenses/ "$ANDROID_HOME/licenses/"

script:
  - ./gradlew assembleRelease