language: android
jdk: oraclejdk8
sudo: false

licenses:
  - android-sdk-license-.+
  - '.+'

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - ConstraintLayout

before_install:
  - chmod +x gradlew

script:
  - mkdir "$ANDROID_SDK/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
  - ./gradlew assembleRelease